#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable jenkins.service

  if test -f "disabled.polar"; then
    echo "jenkins is already disabled."
  else
    touch "disabled.polar"
    if systemctl is-active --quiet jenkins-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop jenkins.service
    else
      echo "jenkins will be disabled on next reboot."
    fi
  fi

fi


