#!/bin/sh

#
# Skip installation screen
# ------------------------

set -e
umask 0022


logger -t "${0}" "Notice: Marking jenkins installation as complete..."

if test ! -f "/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion"; then

  touch "/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion"
  chown jenkins:jenkins "/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion"

fi

