#!/bin/bash

if [ $# -eq 4 ]; then

  instance="${1}"
  virtualhost="${2}"
  url="${3}"

  #
  # Handle jenkins locations

  line=/etc/device/services/app/jenkins

  if test ! -f "$line/virtualhost.d/listen.d/instance.d/name.txt"; then
    exit 0;
  fi
  if test "${instance}" != "$(head -n 1 $line/virtualhost.d/listen.d/instance.d/name.txt)"; then
    exit 0;
  fi
  if test ! -f "$line/virtualhost.d/name.txt"; then
    exit 0;
  fi
  if test "${virtualhost}" != "$(head -n 1 $line/virtualhost.d/name.txt)"; then
    exit 0;
  fi
  virtualhost="$(head -n 1 ${line}/virtualhost.d/name.txt)"
  application="jenkins"

  # read in the path if present
  path=""
  if test -f "${line}/path.txt"; then
    path="$(head -n 1 ${line}/path.txt)"
  fi
  # empty path becomes a /
  if test -z "${path}";then
    path="/"
  fi

  # read in the tlsport if present
  tlsport=""
  if test -f "${line}/virtualhost.d/listen.d/tls-port.txt"; then
    tlsport="$(head -n 1 ${line}/virtualhost.d/listen.d/tls-port.txt)"
  fi
  # empty tls-port becomes 443
  if test -z "${tlsport}";then
    tlsport="443"
  fi

  # read auth if present
  authname=""
  if test -f "$line/auth.d/name.txt"; then
    authname="$(head -n 1 $line/auth.d/name.txt)"
  fi

  echo
  echo "    Application jenkins:"
  echo "      ${url}${path}"

  if test -n "${authname}"; then
    echo "      auth: ${authname}"
  else
    echo "      no-auth: open"
  fi

  if test -f "$line/disabled.bin"; then
    echo "      jenkins: disabled"
  else
    echo -n "      jenkins: "
    SYSTEMD_COLORS=1 systemctl is-active "jenkins" || true
  fi

fi


