#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable jenkins.service

  if test ! -f "disabled.bin"; then
    echo "jenkins is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet jenkins-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart jenkins-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart jenkins.service
    else
      echo "jenkins will be enabled on next reboot."
    fi
  fi

fi

