#!/bin/sh

set -e
umask 0002

OPTIONS="--polar disabled \
	 --polar allow-anonymous \
	 --default all --select-base /usr/share/device/services/app/jenkins/protocol.txt --select protocol \
	 --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost \
	 --relation-base /etc/device/services/www/auth --relation-name name --relation-suffix .txt --relation auth \
	 --required \
	 --url-path-abempty path"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if test -f "disabled.bin"; then
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl --quiet disable jenkins.service
    if systemctl is-active --quiet jenkins-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop jenkins.service
    else
      echo "jenkins will be disabled on next reboot."
    fi
  else
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl --quiet enable jenkins.service
    if systemctl is-active --quiet jenkins-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart jenkins-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart jenkins.service
    else
      echo "jenkins will be enabled on next reboot."
    fi
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

